/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'fromOwner' : IDL.Bool,
});
export const ChatSession = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(ChatMessage),
  'ownerId' : UserId,
  'createdAt' : Time,
  'ended' : IDL.Bool,
  'unreadByOwner' : IDL.Bool,
  'senderId' : IDL.Opt(UserId),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : Time,
  'senderNote' : IDL.Opt(IDL.Text),
  'recipientId' : UserId,
});
export const StickerOrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'printed' : IDL.Null,
  'mailed' : IDL.Null,
});
export const StickerOrder = IDL.Record({
  'status' : StickerOrderStatus,
  'vehicleDescription' : IDL.Text,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Time,
  'orderId' : IDL.Nat,
  'mailingAddress' : IDL.Text,
});
export const SubscriptionStatus = IDL.Record({
  'paidUntil' : IDL.Int,
  'isActive' : IDL.Bool,
  'vehicleCount' : IDL.Nat,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVehicle' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdmin' : IDL.Func([IDL.Text], [], []),
  'createChatSession' : IDL.Func(
      [UserId, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'endChatSession' : IDL.Func([IDL.Text], [], []),
  'getAdminSetupToken' : IDL.Func([], [IDL.Text], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'displayName' : IDL.Text,
            'userId' : UserId,
            'vehicleCount' : IDL.Nat,
            'subscriptionPaidUntil' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatSession' : IDL.Func([IDL.Text], [ChatSession], ['query']),
  'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMessagesByUser' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(StickerOrder)], ['query']),
  'getMySubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getOwnerChatSessions' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
  'getStickerOrders' : IDL.Func([], [IDL.Vec(StickerOrder)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markSessionRead' : IDL.Func([IDL.Text], [], []),
  'markSubscriptionPaid' : IDL.Func([UserId, IDL.Nat], [], []),
  'removeVehicle' : IDL.Func([IDL.Nat], [], []),
  'resetAdminSetupToken' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'sendMessage' : IDL.Func(
      [UserId, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitStickerOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateStickerOrderStatus' : IDL.Func([IDL.Nat, StickerOrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'fromOwner' : IDL.Bool,
  });
  const ChatSession = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(ChatMessage),
    'ownerId' : UserId,
    'createdAt' : Time,
    'ended' : IDL.Bool,
    'unreadByOwner' : IDL.Bool,
    'senderId' : IDL.Opt(UserId),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : Time,
    'senderNote' : IDL.Opt(IDL.Text),
    'recipientId' : UserId,
  });
  const StickerOrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'printed' : IDL.Null,
    'mailed' : IDL.Null,
  });
  const StickerOrder = IDL.Record({
    'status' : StickerOrderStatus,
    'vehicleDescription' : IDL.Text,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Time,
    'orderId' : IDL.Nat,
    'mailingAddress' : IDL.Text,
  });
  const SubscriptionStatus = IDL.Record({
    'paidUntil' : IDL.Int,
    'isActive' : IDL.Bool,
    'vehicleCount' : IDL.Nat,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVehicle' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdmin' : IDL.Func([IDL.Text], [], []),
    'createChatSession' : IDL.Func(
        [UserId, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'endChatSession' : IDL.Func([IDL.Text], [], []),
    'getAdminSetupToken' : IDL.Func([], [IDL.Text], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'displayName' : IDL.Text,
              'userId' : UserId,
              'vehicleCount' : IDL.Nat,
              'subscriptionPaidUntil' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatSession' : IDL.Func([IDL.Text], [ChatSession], ['query']),
    'getInbox' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMessagesByUser' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(StickerOrder)], ['query']),
    'getMySubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
    'getMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getOwnerChatSessions' : IDL.Func([], [IDL.Vec(ChatSession)], ['query']),
    'getStickerOrders' : IDL.Func([], [IDL.Vec(StickerOrder)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markSessionRead' : IDL.Func([IDL.Text], [], []),
    'markSubscriptionPaid' : IDL.Func([UserId, IDL.Nat], [], []),
    'removeVehicle' : IDL.Func([IDL.Nat], [], []),
    'resetAdminSetupToken' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'sendMessage' : IDL.Func(
        [UserId, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitStickerOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateStickerOrderStatus' : IDL.Func(
        [IDL.Nat, StickerOrderStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };